delete from users;
delete from user_roles;
delete from roles_permissions;
insert into users(username, password, password_salt) values('zxh', '123456', null);
insert into user_roles(username, role_name) values('zxh', 'admin');
insert into user_roles(username, role_name) values('zxh', 'role1');
insert into roles_permissions(role_name, permission) values('admin', '+user1+10');
insert into roles_permissions(role_name, permission) values('admin', 'user1:*');
insert into roles_permissions(role_name, permission) values('admin', '+user2+10');
insert into roles_permissions(role_name, permission) values('admin', 'user2:*');
